-- Add receipt tracking columns to payment_transactions table
-- This migration adds columns to track receipt numbers and Healthie document IDs
-- for payment receipts generated by the system

ALTER TABLE payment_transactions
ADD COLUMN IF NOT EXISTS receipt_number VARCHAR(255),
ADD COLUMN IF NOT EXISTS healthie_document_id VARCHAR(255);

-- Add indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_payment_transactions_receipt_number
ON payment_transactions(receipt_number);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_healthie_document_id
ON payment_transactions(healthie_document_id);

-- Add comments for documentation
COMMENT ON COLUMN payment_transactions.receipt_number IS 'Unique receipt number in format RCP-timestamp-random';
COMMENT ON COLUMN payment_transactions.healthie_document_id IS 'Healthie document ID where the receipt PDF is stored';