import { NextRequest, NextResponse } from 'next/server';
import { requireApiUser, UnauthorizedError } from '@/lib/auth';
import { createVial, type NewVialInput } from '@/lib/inventoryQueries';

export const dynamic = 'force-dynamic';

/**
 * Generate sequential vial IDs starting from a base ID
 */
function generateSequentialIds(baseId: string, count: number): string[] {
  const match = baseId.match(/^([A-Za-z]*)(\d+)$/);
  if (!match) {
    // If no number found, append numbers
    return Array.from({ length: count }, (_, i) => `${baseId}${i + 1}`);
  }
  
  const [, prefix, numberStr] = match;
  const startNumber = Number.parseInt(numberStr, 10);
  return Array.from({ length: count }, (_, i) => {
    const num = startNumber + i;
    const padded = num.toString().padStart(numberStr.length, '0');
    return `${prefix}${padded}`;
  });
}

export async function POST(request: NextRequest) {
  try {
    // Parse body first to catch JSON errors early
    let body;
    try {
      body = await request.json();
    } catch (parseError) {
      console.error('[API] JSON parse error:', parseError);
      return NextResponse.json(
        { error: 'Invalid JSON in request body' },
        { status: 400 }
      );
    }

    let user;
    try {
      user = await requireApiUser(request, 'write');
    } catch (authError: any) {
      if (authError instanceof UnauthorizedError || authError.status === 401) {
        return NextResponse.json(
          { error: 'Unauthorized. Please log in.' },
          { status: 401 }
        );
      }
      throw authError;
    }

    const {
      count,
      autoGenerate,
      externalId,
      sizeMl,
      lotNumber,
      expirationDate,
      dateReceived,
      controlledSubstance,
      deaDrugName,
      deaDrugCode,
      location,
      notes
    } = body;

    if (!count || count < 1) {
      return NextResponse.json({ error: 'Count must be at least 1' }, { status: 400 });
    }

    if (count > 100) {
      return NextResponse.json({ error: 'Cannot create more than 100 vials at once' }, { status: 400 });
    }

    const created: Array<{ vial_id: string; external_id: string | null }> = [];
    const errors: string[] = [];

    // If auto-generating, we need to get the next ID from the database
    // If a starting ID is provided, generate sequential IDs
    let vialIds: string[] = [];
    
    if (autoGenerate) {
      // Will be generated by createVial function
      vialIds = Array(count).fill('');
    } else if (externalId) {
      vialIds = generateSequentialIds(externalId, count);
    } else {
      return NextResponse.json({ error: 'Either autoGenerate must be true or externalId must be provided' }, { status: 400 });
    }

    // Create vials one by one (could be optimized with a transaction, but this is safer)
    for (let i = 0; i < count; i++) {
      try {
        const vialInput: NewVialInput = {
          externalId: vialIds[i] || undefined, // Empty string means auto-generate
          sizeMl: sizeMl ? Number(sizeMl) : undefined,
          lotNumber: lotNumber || undefined,
          expirationDate: expirationDate || undefined,
          dateReceived: dateReceived || undefined,
          controlledSubstance: controlledSubstance ?? true,
          deaDrugName: deaDrugName || undefined,
          deaDrugCode: deaDrugCode || undefined,
          location: location || undefined,
          notes: notes || undefined,
          status: 'Active',
          remainingVolumeMl: sizeMl ? Number(sizeMl) : undefined
        };

        const vial = await createVial(vialInput);
        created.push({
          vial_id: vial.vial_id,
          external_id: vial.external_id
        });
      } catch (error: any) {
        errors.push(`Vial ${i + 1}: ${error.message || 'Unknown error'}`);
      }
    }

    if (created.length === 0) {
      return NextResponse.json(
        { 
          error: 'Failed to create any vials',
          errors 
        },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      created,
      errors: errors.length > 0 ? errors : undefined,
      message: `Successfully created ${created.length} of ${count} vial${created.length === 1 ? '' : 's'}`
    });
  } catch (error: any) {
    console.error('[API] Error creating vials:', error);
    
    // Check if it's a JSON parse error
    if (error instanceof SyntaxError || error.message?.includes('JSON') || error.message?.includes('unexpected token')) {
      return NextResponse.json(
        { error: 'Invalid request format. Please check your input data.' },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { error: error.message || 'Failed to create vials' },
      { status: 500 }
    );
  }
}

