#!/bin/bash
# build-spawn-contract.sh — Compose the canonical SPAWN_CONTRACT from its source parts.
#
# Single source of truth: docs/spawn-contract/*.md  +  the LIVE learned-patterns.md.
# This script is the ONLY thing that writes the generated artifacts. Editing the
# generated files by hand will be overwritten on the next build.
#
# Outputs:
#   docs/SPAWN_CONTRACT.md                    full human-readable contract (both surfaces)
#   docs/spawn-contract/SPAWN_CONTRACT.tmux.txt    injectable preamble (on-box tmux)
#   docs/spawn-contract/SPAWN_CONTRACT.cowork.txt  injectable preamble (Cowork cloud)
# and mirrors the two .txt to ~/.claude/coord/ so on-box spawners can read them.
#
# Why a snapshot of learned-patterns is embedded: Cowork cloud sessions can't read
# ~/.claude/coord, so we bake Phil's latest corrections into the committed contract.
# Re-run this whenever learned-patterns.md changes, then commit.
#
# Usage: bash scripts/build-spawn-contract.sh
set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
SRC="$REPO_ROOT/docs/spawn-contract"
LEARNED="${LEARNED_PATTERNS_FILE:-$HOME/.claude/coord/learned-patterns.md}"
COORD_DIR="$HOME/.claude/coord"
STAMP="$(date '+%Y-%m-%d %H:%M %Z')"

GEN_WARNING="<!-- GENERATED by scripts/build-spawn-contract.sh — DO NOT EDIT BY HAND.
     Edit the source parts in docs/spawn-contract/*.md and re-run the generator. -->"

# Pull the live learned-patterns snapshot (graceful fallback when off-box, e.g. in cloud).
if [[ -f "$LEARNED" ]]; then
  LEARNED_SNAPSHOT="$(cat "$LEARNED")"
  LEARNED_SRC="snapshot of $LEARNED as of $STAMP"
else
  LEARNED_SNAPSHOT="_(learned-patterns.md not found on this host — regenerate on-box to embed Phil's latest corrections.)_"
  LEARNED_SRC="UNAVAILABLE on this host"
fi

emit_learned() {
  printf '## Learned Patterns (Phil — HIGHEST PRIORITY, overrides defaults)\n\n'
  printf '> %s\n\n' "$LEARNED_SRC"
  printf '%s\n' "$LEARNED_SNAPSHOT"
}

# ---- docs/SPAWN_CONTRACT.md : full contract, both surfaces -------------------
{
  echo "$GEN_WARNING"
  echo
  echo "# SPAWN_CONTRACT"
  echo
  echo "_Generated $STAMP. Every Cowork task and tmux session spawned by Dispatch"
  echo "inherits this contract. Source: \`docs/spawn-contract/*.md\` + live learned-patterns._"
  echo
  cat "$SRC/standing-rules.md"; echo
  echo "---"; echo
  cat "$SRC/capability-matrix.md"; echo
  echo "---"; echo
  cat "$SRC/preflight-tmux.md"; echo
  echo "---"; echo
  cat "$SRC/preflight-cowork.md"; echo
  echo "---"; echo
  emit_learned
} > "$REPO_ROOT/docs/SPAWN_CONTRACT.md"

# ---- shared header for the injectable preambles ------------------------------
preamble_header() {
  local surface="$1"
  echo "===== SPAWN_CONTRACT ($surface) — generated $STAMP ====="
  echo "This contract governs your session. Follow it throughout, above any default behavior."
  echo
}

# ---- SPAWN_CONTRACT.tmux.txt : on-box injectable -----------------------------
{
  preamble_header "tmux / on-box"
  cat "$SRC/standing-rules.md"; echo
  cat "$SRC/capability-matrix.md"; echo
  cat "$SRC/preflight-tmux.md"; echo
  emit_learned
} > "$SRC/SPAWN_CONTRACT.tmux.txt"

# ---- SPAWN_CONTRACT.cowork.txt : cloud injectable ----------------------------
{
  preamble_header "Cowork / cloud"
  cat "$SRC/standing-rules.md"; echo
  cat "$SRC/capability-matrix.md"; echo
  cat "$SRC/preflight-cowork.md"; echo
  emit_learned
} > "$SRC/SPAWN_CONTRACT.cowork.txt"

# ---- mirror the injectables to coord state for on-box spawners ---------------
if [[ -d "$COORD_DIR" ]]; then
  cp "$SRC/SPAWN_CONTRACT.tmux.txt"   "$COORD_DIR/spawn-contract.tmux.txt"
  cp "$SRC/SPAWN_CONTRACT.cowork.txt" "$COORD_DIR/spawn-contract.cowork.txt"
  echo "✓ Mirrored to $COORD_DIR/spawn-contract.{tmux,cowork}.txt"
else
  echo "⚠ $COORD_DIR not present (off-box?) — skipped coord mirror."
fi

echo "✓ Built docs/SPAWN_CONTRACT.md and injectable preambles ($LEARNED_SRC)."
