#!/bin/bash
# =============================================================================
# GMH Dashboard Live Status Report Generator
# Queries PM2, disk, Postgres, and service health to produce LIVE_STATUS.md
# Usage: bash ~/gmhdashboard/scripts/generate-status-report.sh
# Output: ~/gmhdashboard/docs/LIVE_STATUS.md
# =============================================================================

set -euo pipefail

REPORT_FILE="$HOME/gmhdashboard/docs/LIVE_STATUS.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')
ENV_FILE="$HOME/gmhdashboard/.env.local"

# Load database credentials from .env.local
if [ -f "$ENV_FILE" ]; then
  export DATABASE_HOST=$(grep '^DATABASE_HOST=' "$ENV_FILE" | cut -d'=' -f2-)
  export DATABASE_PORT=$(grep '^DATABASE_PORT=' "$ENV_FILE" | cut -d'=' -f2-)
  export DATABASE_NAME=$(grep '^DATABASE_NAME=' "$ENV_FILE" | cut -d'=' -f2-)
  export DATABASE_USER=$(grep '^DATABASE_USER=' "$ENV_FILE" | cut -d'=' -f2-)
  export DATABASE_PASSWORD=$(grep '^DATABASE_PASSWORD=' "$ENV_FILE" | cut -d'=' -f2-)
fi

# Helper: run psql query
run_sql() {
  PGPASSWORD="$DATABASE_PASSWORD" psql -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$DATABASE_USER" -d "$DATABASE_NAME" -t -A -c "$1" 2>/dev/null || echo "QUERY_FAILED"
}

echo "Generating live status report..."

# --- Collect Data ---

# PM2 Status
PM2_JSON=$(pm2 jlist 2>/dev/null || echo '[]')
PM2_SUMMARY=$(echo "$PM2_JSON" | python3 -c '
import sys, json
try:
    data = json.load(sys.stdin)
    online = sum(1 for p in data if p["pm2_env"]["status"] == "online")
    total = len(data)
    high_restarts = [(p["name"], p["pm2_env"]["restart_time"]) for p in data if p["pm2_env"]["restart_time"] > 5]
    print(f"| Services Online | {online}/{total} |" )
    for name, restarts in high_restarts:
        print(f"| ⚠️  {name} | {restarts} restarts |" )
except:
    print("| PM2 | ERROR reading status |")
' 2>/dev/null)

PM2_TABLE=$(echo "$PM2_JSON" | python3 -c '
import sys, json
try:
    data = json.load(sys.stdin)
    for p in data:
        name = p["name"]
        status = p["pm2_env"]["status"]
        restarts = p["pm2_env"]["restart_time"]
        mem = round(p["monit"]["memory"] / 1024 / 1024, 1)
        cpu = p["monit"]["cpu"]
        icon = "✅" if status == "online" else "🔴"
        print(f"| {icon} {name} | {status} | {restarts} | {mem}MB | {cpu}% |" )
except:
    print("| ERROR | - | - | - | - |")
' 2>/dev/null)

# Disk Usage
DISK_LINE=$(df -h / | tail -1)
DISK_USED=$(echo "$DISK_LINE" | awk '{print $3}')
DISK_AVAIL=$(echo "$DISK_LINE" | awk '{print $4}')
DISK_PCT=$(echo "$DISK_LINE" | awk '{print $5}')

# System Load
LOAD_AVG=$(uptime | awk -F'load average: ' '{print $2}')
MEM_INFO=$(free -m | awk '/Mem:/ {printf "%dMB / %dMB (%.0f%%)", $3, $2, $3/$2*100}')

# Database Queries
PATIENT_COUNT=$(run_sql "SELECT COUNT(*) FROM patients WHERE status_key = 'active'")
BILLING_HOLDS=$(run_sql "SELECT COUNT(*) FROM patients WHERE status_key = 'hold_payment_research'")
PENDING_LABS=$(run_sql "SELECT COUNT(*) FROM lab_review_queue WHERE status = 'pending'" 2>/dev/null || echo "0")
TOTAL_PATIENTS=$(run_sql "SELECT COUNT(*) FROM patients")

# GHL Sync Status
GHL_PENDING=$(run_sql "SELECT COUNT(*) FROM patients WHERE ghl_sync_status = 'pending' OR ghl_sync_status IS NULL" 2>/dev/null || echo "N/A")
GHL_SYNCED=$(run_sql "SELECT COUNT(*) FROM patients WHERE ghl_sync_status = 'synced'" 2>/dev/null || echo "N/A")
GHL_ERROR=$(run_sql "SELECT COUNT(*) FROM patients WHERE ghl_sync_status = 'error'" 2>/dev/null || echo "N/A")

# Recent service restarts (last 24h via PM2)
RECENT_RESTARTS=$(echo "$PM2_JSON" | python3 -c '
import sys, json
try:
    data = json.load(sys.stdin)
    recent = [(p["name"], p["pm2_env"]["restart_time"]) for p in data if p["pm2_env"]["restart_time"] > 0]
    if recent:
        for name, r in sorted(recent, key=lambda x: -x[1]):
            print(f"- {name}: {r} restarts")
    else:
        print("- No restarts recorded")
except:
    print("- Error reading restart data")
' 2>/dev/null)

# --- Write Report ---

cat > "$REPORT_FILE" << EOF
# GMH Dashboard — Live Status Report

**Generated**: $TIMESTAMP
**Server**: EC2 (us-east-2) | Amazon Linux

---

## System Health

| Metric | Value |
|--------|-------|
| Disk Used | $DISK_USED / $DISK_AVAIL available ($DISK_PCT) |
| Memory | $MEM_INFO |
| Load Average | $LOAD_AVG |
$PM2_SUMMARY

---

## PM2 Services

| Service | Status | Restarts | Memory | CPU |
|---------|--------|----------|--------|-----|
$PM2_TABLE

---

## Database (Postgres)

| Metric | Value |
|--------|-------|
| Total Patients | $TOTAL_PATIENTS |
| Active Patients | $PATIENT_COUNT |
| Billing Holds | $BILLING_HOLDS |
| Pending Lab Reviews | $PENDING_LABS |

---

## GHL Sync Status

| Status | Count |
|--------|-------|
| Synced | $GHL_SYNCED |
| Pending | $GHL_PENDING |
| Error | $GHL_ERROR |

---

## Recent Service Restarts

$RECENT_RESTARTS

---

*Auto-generated by generate-status-report.sh — do not edit manually.*
EOF

echo "✅ Status report written to $REPORT_FILE"
